version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: emby-proxy
    ports:
      - "8011:8001"
      - "8999:8999"
    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PROXY_CONTAINER_NAME=emby-proxy
      - PROXY_CORE_URL=http://localhost:8999
    restart: unless-stopped
